# Generated by Django 5.0.2 on 2024-09-11 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9991234567890'. Country code must be 1-3 digits followed by a 10-digit number.", regex='^\\+\\d{1,3}\\d{10}$')])),
                ('room_num', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('room_type', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
